version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - demo-app

  demo-app:
    image: tmddnjs3369/cnabro_be:latest
    volumes:
      - ./.dockervenv:/src/.venv
      - .:/src
    expose:
      - "8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
