version: '3'
services:
  service:
    image: nginx
    ports:
      - "80:80"  # 외부에서 포트 80으로 접속, Nginx 컨테이너의 포트 80으로 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - demo-app

  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    expose:
      - "8000" 
    environment:
      - WATCHFILES_FORCE_POLLING=true
  
volumes:
  mysql_data:


