"""empty message

Revision ID: c2314f842a4d
Revises: 3ba4b02bcfb1
Create Date: 2024-11-09 14:46:16.528712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c2314f842a4d'
down_revision: Union[str, None] = '3ba4b02bcfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False, comment='유저고유번호'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='유저고유번호'),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jwt_record')
    op.alter_column('agreement', 'agree_term',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_comment='이용약관 동의 여부')
    op.alter_column('agreement', 'agree_privacy',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_comment='개인정보 동의 여부')
    op.alter_column('agreement', 'create_at',
               existing_type=mysql.TIMESTAMP(),
               comment='생성시간',
               existing_comment='생성시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('agreement', 'agree_sensitive')
    op.alter_column('login_log', 'login_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='로그인 시각')
    op.drop_column('login_log', 'login_IP')
    op.add_column('note', sa.Column('update_at', sa.TIMESTAMP(), nullable=True, comment='수정 시각'))
    op.alter_column('note', 'score',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=2),
               comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_comment='점수',
               existing_nullable=False)
    op.drop_column('note', 'edit_at')
    op.drop_column('refresh_token', 'token_type')
    op.add_column('user', sa.Column('provider_id', sa.Integer(), nullable=True, comment='OaOauth 제공자가 local이 아닌 경우에만 작성'))
    op.add_column('user', sa.Column('provider_type', sa.String(length=20), nullable=False, comment='Oauth 제공자 정보'))
    op.add_column('user', sa.Column('nickname', sa.String(length=20), nullable=False, comment='유저 닉네임'))
    op.add_column('user', sa.Column('update_at', sa.DateTime(), nullable=True, comment='최종수정시각'))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=320),
               existing_comment='유저 이메일',
               existing_nullable=False)
    op.drop_column('user', 'last_login_datetime')
    op.drop_column('user', 'last_update_datetime')
    op.drop_column('user', 'user_nickname')
    op.drop_column('user', 'mobile_number')
    op.drop_column('user', 'last_login_IP')
    op.drop_column('user', 'email_agreement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_agreement', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='이메일 동의 여부'))
    op.add_column('user', sa.Column('last_login_IP', mysql.VARCHAR(length=50), nullable=False, comment='최종 로그인 IP'))
    op.add_column('user', sa.Column('mobile_number', mysql.VARCHAR(length=11), nullable=False, comment='유저 전화번호'))
    op.add_column('user', sa.Column('user_nickname', mysql.VARCHAR(length=10), nullable=False, comment='유저 닉네임'))
    op.add_column('user', sa.Column('last_update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='최종 변경 시각'))
    op.add_column('user', sa.Column('last_login_datetime', mysql.DATETIME(), nullable=False, comment='최종 로그인 시각'))
    op.alter_column('user', 'email',
               existing_type=sa.String(length=320),
               type_=mysql.VARCHAR(length=30),
               existing_comment='유저 이메일',
               existing_nullable=False)
    op.drop_column('user', 'update_at')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'provider_type')
    op.drop_column('user', 'provider_id')
    op.add_column('refresh_token', sa.Column('token_type', mysql.INTEGER(), autoincrement=False, nullable=True, comment='토큰 유형 (0: Email, 1: Google, 2: Apple)'))
    op.add_column('note', sa.Column('edit_at', mysql.TIMESTAMP(), nullable=True, comment='수정 시각'))
    op.alter_column('note', 'score',
               existing_type=sa.LargeBinary(length=2),
               type_=mysql.TINYBLOB(),
               comment='점수',
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    op.drop_column('note', 'update_at')
    op.add_column('login_log', sa.Column('login_IP', mysql.VARCHAR(length=50), nullable=True, comment='로그인 IP'))
    op.alter_column('login_log', 'login_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='로그인 시각')
    op.add_column('agreement', sa.Column('agree_sensitive', mysql.INTEGER(), autoincrement=False, nullable=True, comment='민감정보 동의 여부'))
    op.alter_column('agreement', 'create_at',
               existing_type=mysql.TIMESTAMP(),
               comment='생성시각',
               existing_comment='생성시간',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('agreement', 'agree_privacy',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               nullable=True,
               existing_comment='개인정보 동의 여부')
    op.alter_column('agreement', 'agree_term',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               nullable=True,
               existing_comment='이용약관 동의 여부')
    op.create_table('jwt_record',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='발급 고유번호'),
    sa.Column('refresh_token_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='리프레쉬토큰 고유번호'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='유저고유번호'),
    sa.Column('ip_address', mysql.VARCHAR(length=20), nullable=True, comment='아이피 주소'),
    sa.Column('expire_datetime', mysql.DATETIME(), nullable=False, comment='만료일시'),
    sa.Column('logout_at', mysql.TIMESTAMP(), nullable=True, comment='로그아웃 시각'),
    sa.Column('create_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='생성시각'),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refresh_token.id'], name='jwt_record_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='jwt_record_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tag_note')
    # ### end Alembic commands ###
