"""empty message

Revision ID: c7efc31d1a0e
Revises: ee597262aeb3
Create Date: 2024-11-21 20:55:00.467854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7efc31d1a0e'
down_revision: Union[str, None] = 'ee597262aeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_log', 'login_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_comment='로그인 시각',
               existing_nullable=False)
    op.alter_column('note', 'score',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=2),
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'score',
               existing_type=sa.LargeBinary(length=2),
               type_=mysql.TINYBLOB(),
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    op.alter_column('login_log', 'login_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_comment='로그인 시각',
               existing_nullable=False)
    # ### end Alembic commands ###
