"""empty message

Revision ID: dc3c0b9ac259
Revises: c2314f842a4d
Create Date: 2024-11-09 15:37:56.880910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc3c0b9ac259'
down_revision: Union[str, None] = 'c2314f842a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'score',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=2),
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=320),
               type_=sa.String(length=100),
               existing_comment='유저 이메일',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=60),
               existing_comment='유저 비밀번호',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=20),
               existing_comment='유저 비밀번호',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=320),
               existing_comment='유저 이메일',
               existing_nullable=False)
    op.alter_column('note', 'score',
               existing_type=sa.LargeBinary(length=2),
               type_=mysql.TINYBLOB(),
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    # ### end Alembic commands ###
