"""empty message

Revision ID: e7e2643de6ef
Revises: bf71f1b8d36f
Create Date: 2024-11-11 14:56:05.994122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7e2643de6ef'
down_revision: Union[str, None] = 'bf71f1b8d36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'score',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=2),
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    op.alter_column('user', 'provider_id',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=30),
               existing_comment='OaOauth 제공자가 local이 아닌 경우에만 작성',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'provider_id',
               existing_type=sa.String(length=30),
               type_=mysql.BIGINT(),
               existing_comment='OaOauth 제공자가 local이 아닌 경우에만 작성',
               existing_nullable=True)
    op.alter_column('note', 'score',
               existing_type=sa.LargeBinary(length=2),
               type_=mysql.TINYBLOB(),
               existing_comment='집중 단계를 0~3까지 4단계를 2비트로 표현',
               existing_nullable=False)
    # ### end Alembic commands ###
