name: Build, Push Docker Image, and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t tmddnjs3369/cnabro_be:latest .
          docker push tmddnjs3369/cnabro_be:latest

      # 4. AWS EC2로 Rolling Deploy
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@<EC2_IP_ADDRESS> << 'EOF'
            # 기존 screen 세션 종료 (선택적)
            screen -S docker -X quit || true
      
            # 새 screen 세션 시작 및 docker-compose 실행
            screen -S docker -d -m
            screen -S docker -p 0 -X stuff 'cd /path/to/docker-compose/project && docker-compose down && docker-compose pull && docker-compose up -d\n'
          EOF

