name: Build, Push Docker Image, and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t tmddnjs3369/cnabro_be:latest .
          docker push tmddnjs3369/cnabro_be:latest

      # 4. AWS EC2로 Rolling Deploy
      - name: Rolling Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@3.36.117.123 << 'EOF'
            cd /path/to/docker-compose/project
            docker-compose pull
            docker-compose up -d --no-deps --build demo-app
          EOF
